/**
 * TypeScript types auto-derived from the Supabase schema.
 * Regenerate with: npx supabase gen types typescript --project-id <your-project-id> > lib/supabase/database.types.ts
 *
 * These types are hand-written to match schema.sql until you connect
 * the Supabase CLI and run the generator.
 */

export type AppointmentStatus =
  | "pending"
  | "confirmed"
  | "in-progress"
  | "completed"
  | "cancelled";

export type Database = {
  public: {
    Tables: {
      appointments: {
        Row: {
          id: string;
          booking_ref: string;
          client_name: string;
          client_phone: string;
          client_email: string | null;
          pet_name: string;
          pet_type: string;
          pet_breed: string | null;
          pet_age: string | null;
          service_type: string;
          preferred_date: string;          // ISO date "YYYY-MM-DD"
          preferred_time: string;          // "HH:MM:SS"
          address: string;
          city: string;
          pin_lat: number | null;
          pin_lng: number | null;
          status: AppointmentStatus;
          notes: string | null;
          is_emergency: boolean;
          admin_notes: string | null;
          created_at: string;              // ISO timestamptz
        };
        Insert: {
          id?: string;
          booking_ref?: string;            // auto-generated by trigger
          client_name: string;
          client_phone: string;
          client_email?: string | null;
          pet_name: string;
          pet_type: string;
          pet_breed?: string | null;
          pet_age?: string | null;
          service_type: string;
          preferred_date: string;
          preferred_time: string;
          address: string;
          city: string;
          pin_lat?: number | null;
          pin_lng?: number | null;
          status?: AppointmentStatus;
          notes?: string | null;
          is_emergency?: boolean;
          admin_notes?: string | null;
          created_at?: string;
        };
        Update: {
          status?: AppointmentStatus;
          admin_notes?: string | null;
          preferred_date?: string;
          preferred_time?: string;
          address?: string;
          city?: string;
          notes?: string | null;
          is_emergency?: boolean;
        };
      };

      time_slot_blocks: {
        Row: {
          id: string;
          blocked_date: string;
          blocked_time: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          blocked_date: string;
          blocked_time: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          reason?: string | null;
        };
      };

      services: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          duration_minutes: number;
          price_min: number | null;
          price_max: number | null;
          icon: string | null;
          is_active: boolean;
          is_emergency: boolean;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          duration_minutes?: number;
          price_min?: number | null;
          price_max?: number | null;
          icon?: string | null;
          is_active?: boolean;
          is_emergency?: boolean;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          duration_minutes?: number;
          price_min?: number | null;
          price_max?: number | null;
          icon?: string | null;
          is_active?: boolean;
          is_emergency?: boolean;
          display_order?: number;
        };
      };

      contact_messages: {
        Row: {
          id: string;
          name: string;
          phone: string;
          email: string | null;
          subject: string | null;
          message: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          email?: string | null;
          subject?: string | null;
          message: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          is_read?: boolean;
        };
      };
    };

    Views: {
      v_today_appointments: {
        Row: {
          id: string;
          booking_ref: string;
          client_name: string;
          client_phone: string;
          pet_name: string;
          pet_type: string;
          service_type: string;
          preferred_time: string;
          address: string;
          city: string;
          status: AppointmentStatus;
          is_emergency: boolean;
          created_at: string;
        };
      };
      v_appointment_stats: {
        Row: {
          total: number;
          today_total: number;
          pending: number;
          confirmed: number;
          in_progress: number;
          completed_today: number;
          emergencies_today: number;
          total_clients: number;
          this_month: number;
        };
      };
    };

    Functions: {
      generate_booking_ref: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
  };
};

// Shorthand row types for convenient use across the codebase
export type AppointmentRow = Database["public"]["Tables"]["appointments"]["Row"];
export type AppointmentInsert = Database["public"]["Tables"]["appointments"]["Insert"];
export type AppointmentUpdate = Database["public"]["Tables"]["appointments"]["Update"];
export type ServiceRow = Database["public"]["Tables"]["services"]["Row"];
export type TimeSlotBlockRow = Database["public"]["Tables"]["time_slot_blocks"]["Row"];
export type ContactMessageRow = Database["public"]["Tables"]["contact_messages"]["Row"];
export type ContactMessageInsert = Database["public"]["Tables"]["contact_messages"]["Insert"];
export type AppointmentStatsRow = Database["public"]["Views"]["v_appointment_stats"]["Row"];
